version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:15
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine
    # restart: always
    # ports:
    #   - '6379:6379'

  celery:
    restart: always
    build:
      context: .
    # command: celery -A api_swipe worker --loglevel=info
    depends_on:
      - db
      - redis
      - web


  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A config.celery worker --beat
    env_file:
      - ./.env.dev
    depends_on:
      - celery
      - db
      - redis
      - web

volumes:
  postgres_data: