version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # - ./:/usr/src/app/
      # - static_volume:/home/app/web/staticfiles
      # - media_volume:/home/app/web/mediafiles
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      # - redis

  db:
    image: postgres:15
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine
    depends_on:
      - web

  celery:
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
    - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
    - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: