# Generated by Django 3.2.20 on 2023-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_accomodations',
            field=models.ManyToManyField(blank=True, to='ads.Accomodation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_adds',
            field=models.ManyToManyField(blank=True, to='ads.Ads'),
        ),
    ]
