# Generated by Django 3.2.20 on 2023-07-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230722_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_false',
            field=models.BooleanField(default=False),
        ),
    ]
