# Generated by Django 3.2.20 on 2023-07-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_false'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_false',
            new_name='is_activated',
        ),
    ]
