# Generated by Django 3.2.20 on 2023-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_nontifications_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agent_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agent_second_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
