# Generated by Django 3.2.20 on 2023-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230725_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Subscription_last_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
