# Generated by Django 3.2.20 on 2023-07-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscription_subscription_last_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscription_last_date',
            new_name='subscription_last_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_auto_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
