# Generated by Django 3.2.20 on 2023-07-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230726_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
