# Generated by Django 3.2.20 on 2023-07-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagePerHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('floor_schema', models.ImageField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('floor_schema', models.ImageField(blank=True, null=True, upload_to='galery/floor_schemas/')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('disctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('microdisctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('house_status', models.CharField(choices=[('квартири', 'appartments'), ('квартири з терассами', 'appartments_with_terrace'), ('пентхауз', 'penthouse')], max_length=200)),
                ('house_type', models.CharField(choices=[('багатоквартирним', 'flats'), ('таунхауз', 'townhouse'), ('коттедж', 'cottage')], max_length=200)),
                ('house_class', models.CharField(choices=[('елітний', 'elite'), ('мейнстрім', 'mainstreem'), ('економ+', 'econom+')], max_length=200)),
                ('building_technology', models.CharField(choices=[('моноблок', 'monoblock'), ('цегла та плити', 'brick_and_slab'), ('цегла та деревина', 'brick_and_wood')], max_length=200)),
                ('square_type', models.CharField(choices=[('закрита з охороною', 'closed_with_guard'), ('закрита з вахтером', 'closed_with_watchman'), ('відкрита з вахтером', 'open_with_watchman')], max_length=200)),
                ('distance_to_sea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('services_payment', models.CharField(choices=[('Платежи', 'payments'), ('керуюча компанія', 'management_company')], max_length=200)),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household_gas', models.CharField(choices=[('є', 'yes'), ('ні', 'no'), ('тільки опалення', 'only_heating')], max_length=200)),
                ('heating', models.CharField(choices=[('центральне', 'central'), ('індивідуальне', 'individual')], max_length=200)),
                ('sewage', models.CharField(choices=[('центральне', 'central'), ('індивідуальна', 'individual')], max_length=200)),
                ('plumbing', models.CharField(choices=[('центральне', 'central'), ('індивідуальна', 'individual')], max_length=200)),
                ('registration', models.CharField(choices=[('юстиція', 'judiciary'), ('міжнарода', 'international')], max_length=200)),
                ('type_of_account', models.CharField(choices=[('іпотека', 'mortrage'), ('credit', 'кредит'), ('full_account', 'полная'), ('prepfyment_with_discount', 'предоплата со скидкой')], max_length=200)),
                ('purpose', models.CharField(choices=[('житлова', 'dwelling'), ('торгівельна', 'commercial')], max_length=200)),
                ('summ_of_threaty', models.CharField(choices=[('не повна', 'not_a_complete'), ('повна', 'full')], max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='galery/houses_main_images/')),
                ('location', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPerHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house')),
            ],
        ),
    ]
