# Generated by Django 3.2.21 on 2023-09-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagePerHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('floor_schema', models.ImageField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('floor_schema', models.ImageField(blank=True, null=True, upload_to='galery/floor_schemas/')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('disctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('microdisctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('house_status', models.CharField(blank=True, choices=[('appartments', 'квартири'), ('appartments_with_terrace', 'квартири з терассами'), ('penthouse', 'пентхауз'), ('individual_house', 'індивідуальний будинок')], max_length=200, null=True)),
                ('house_type', models.CharField(blank=True, choices=[('flats', 'багатоквартирним'), ('townhouse', 'таунхауз'), ('cottage', 'коттедж')], max_length=200)),
                ('house_class', models.CharField(blank=True, choices=[('elite', 'елітний'), ('mainstreem', 'мейнстрім'), ('econom+', 'економ+')], max_length=200)),
                ('building_technology', models.CharField(blank=True, choices=[('monoblock', 'моноблок'), ('brick_and_slab', 'цегла та плити'), ('brick_and_wood', 'цегла та деревина')], max_length=200)),
                ('square_type', models.CharField(blank=True, choices=[('closed_with_guard', 'закрита з охороною'), ('closed_with_watchman', 'закрита з вахтером'), ('open_with_watchman', 'відкрита з вахтером')], max_length=200)),
                ('distance_to_sea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('services_payment', models.CharField(blank=True, choices=[('payments', 'Платежи'), ('management_company', 'керуюча компанія')], max_length=200)),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('household_gas', models.CharField(blank=True, choices=[('yes', 'є'), ('no', 'ні'), ('only_heating', 'тільки опалення')], max_length=200)),
                ('heating', models.CharField(blank=True, choices=[('central', 'центральне'), ('individual', 'індивідуальне')], max_length=200)),
                ('sewage', models.CharField(blank=True, choices=[('central', 'центральне'), ('individual', 'індивідуальна')], max_length=200)),
                ('plumbing', models.CharField(blank=True, choices=[('central', 'центральне'), ('individual', 'індивідуальна')], max_length=200)),
                ('sales_department_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_department_surname', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_department_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_department_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('registration', models.CharField(blank=True, choices=[('judiciary', 'юстиція'), ('international', 'міжнарода')], max_length=200)),
                ('type_of_account', models.CharField(blank=True, choices=[('mortrage', 'іпотека'), ('credit', 'кредит'), ('full_account', 'полная'), ('prepfyment_with_discount', 'предоплата со скидкой')], max_length=200)),
                ('purpose', models.CharField(blank=True, choices=[('dwelling', 'житлова'), ('commercial', 'торгівельна')], max_length=200)),
                ('summ_of_threaty', models.CharField(blank=True, choices=[('not_a_complete', 'не повна'), ('full', 'повна')], max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='galery/houses_main_images/')),
                ('location_x', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('location_y', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riser', to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPerHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_entrance', to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_building', to='houses.house')),
            ],
        ),
    ]
