# Generated by Django 3.2.21 on 2023-09-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='image_field',
            field=models.ManyToManyField(blank=True, related_name='house', to='ads.ImageGalery'),
        ),
        migrations.AddField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor', to='houses.house'),
        ),
        migrations.AddField(
            model_name='advantageperhouse',
            name='house',
            field=models.ManyToManyField(to='houses.House'),
        ),
    ]
