# Generated by Django 3.2.20 on 2023-08-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='sales_department',
            new_name='builder',
        ),
        migrations.AddField(
            model_name='house',
            name='sales_department_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='sales_department_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='sales_department_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='sales_department_surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
