# Generated by Django 3.2.20 on 2023-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type_of_account',
            field=models.CharField(choices=[('іпотека', 'mortrage'), ('кредит', 'credit'), ('полная', 'full_account'), ('предоплата со скидкой', 'prepfyment_with_discount')], max_length=200),
        ),
    ]
