# Generated by Django 3.2.20 on 2023-08-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20230801_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='housebuilding',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_building', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='houseentrance',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_entrance', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='riser',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riser', to='houses.house'),
        ),
    ]
