# Generated by Django 3.2.20 on 2023-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_type_of_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_status',
            field=models.CharField(blank=True, choices=[('квартири', 'appartments'), ('квартири з терассами', 'appartments_with_terrace'), ('пентхауз', 'penthouse'), ('індивідуальний будинок', 'individual_house')], max_length=200, null=True),
        ),
    ]
