# Generated by Django 3.2.20 on 2023-08-09 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0004_auto_20230808_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to=settings.AUTH_USER_MODEL),
        ),
    ]
