# Generated by Django 3.2.20 on 2023-08-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_house_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='date_added',
        ),
    ]
