# Generated by Django 3.2.20 on 2023-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_accomodation'),
        ('houses', '0007_remove_house_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='main_image',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ManyToManyField(to='ads.ImageGalery'),
        ),
    ]
