# Generated by Django 3.2.20 on 2023-08-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20230812_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='image',
            new_name='image_field',
        ),
    ]
