# Generated by Django 3.2.20 on 2023-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_rename_image_house_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image_field',
        ),
        migrations.AddField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='galery/houses_main_images/'),
        ),
    ]
