# Generated by Django 3.2.20 on 2023-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_accomodation'),
        ('houses', '0010_auto_20230813_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='main_image',
        ),
        migrations.AddField(
            model_name='house',
            name='image_field',
            field=models.ManyToManyField(related_name='house', to='ads.ImageGalery'),
        ),
    ]
