# Generated by Django 3.2.20 on 2023-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20230813_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='galery/houses_main_images/'),
        ),
    ]
