# Generated by Django 3.2.20 on 2023-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_house_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.AddField(
            model_name='house',
            name='location_x',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='location_y',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
