# Generated by Django 3.2.20 on 2023-08-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_accomodation_is_shown_in_chesboard'),
        ('houses', '0013_auto_20230815_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_field',
            field=models.ManyToManyField(blank=True, null=True, related_name='house', to='ads.ImageGalery'),
        ),
    ]
