# Generated by Django 3.2.20 on 2023-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_alter_house_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_technology',
            field=models.CharField(blank=True, choices=[('monoblock', 'моноблок'), ('brick_and_slab', 'цегла та плити'), ('brick_and_wood', 'цегла та деревина')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating',
            field=models.CharField(blank=True, choices=[('central', 'центральне'), ('individual', 'індивідуальне')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_class',
            field=models.CharField(blank=True, choices=[('elite', 'елітний'), ('mainstreem', 'мейнстрім'), ('econom+', 'економ+')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('flats', 'багатоквартирним'), ('townhouse', 'таунхауз'), ('cottage', 'коттедж')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='household_gas',
            field=models.CharField(blank=True, choices=[('yes', 'є'), ('no', 'ні'), ('only_heating', 'тільки опалення')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='plumbing',
            field=models.CharField(blank=True, choices=[('central', 'центральне'), ('individual', 'індивідуальна')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='purpose',
            field=models.CharField(blank=True, choices=[('dwelling', 'житлова'), ('commercial', 'торгівельна')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='registration',
            field=models.CharField(blank=True, choices=[('judiciary', 'юстиція'), ('international', 'міжнарода')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='services_payment',
            field=models.CharField(blank=True, choices=[('payments', 'Платежи'), ('management_company', 'керуюча компанія')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='sewage',
            field=models.CharField(blank=True, choices=[('central', 'центральне'), ('individual', 'індивідуальна')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='square_type',
            field=models.CharField(blank=True, choices=[('closed_with_guard', 'закрита з охороною'), ('closed_with_watchman', 'закрита з вахтером'), ('open_with_watchman', 'відкрита з вахтером')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='summ_of_threaty',
            field=models.CharField(blank=True, choices=[('not_a_complete', 'не повна'), ('full', 'повна')], max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_of_account',
            field=models.CharField(blank=True, choices=[('mortrage', 'іпотека'), ('credit', 'кредит'), ('full_account', 'полная'), ('prepfyment_with_discount', 'предоплата со скидкой')], max_length=200),
        ),
    ]
