# Generated by Django 3.2.20 on 2023-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_auto_20230830_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
