# Generated by Django 3.2.20 on 2023-09-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_alter_house_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='disctrict',
            new_name='disctrict',
        ),
    ]
