# Generated by Django 3.2.21 on 2023-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_accomodation_planing'),
        ('houses', '0017_rename_disctrict_house_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_field',
            field=models.ManyToManyField(blank=True, related_name='house', to='ads.ImageGalery'),
        ),
    ]
