# Generated by Django 3.2.20 on 2023-07-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_status', models.CharField(choices=[('новобудова', 'new_building'), ('вторинне житло', 'resale_property'), ('коттедж', 'cottage')], max_length=200)),
                ('number', models.PositiveSmallIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('planing', models.CharField(choices=[('студія з санвузлом', 'studio_appartment_with_barhroom'), ('студія з санвузлом і однією спальнею', 'studio_appartment_with_barhroom_and_one bedroom'), ('двокімнатна', 'two_bedroom'), ('двокімнатна зі своєю кришею', 'two_bedroom_and_roof'), ('трьокімнатна', 'three_vedroom'), ('трьокімнатна зі своєю кришею', 'three_vedroom_and_roof')], max_length=200)),
                ('living_condition', models.CharField(choices=[('вимагає ремонту', 'need_repair'), ('готова для заселення', 'reary_for_settlement')], max_length=200)),
                ('area_kitchen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('have_balcony', models.BooleanField()),
                ('heat_type', models.CharField(choices=[('газове', 'gas'), ('електричний', 'electric'), ("дров'яне опалення", 'wood_heating')], max_length=200)),
                ('schema', models.ImageField(blank=True, null=True, upload_to='galery/appartment_schemas/')),
            ],
        ),
        migrations.CreateModel(
            name='DeniedCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galery/image_galery/')),
            ],
        ),
        migrations.CreateModel(
            name='PromoAdditionalPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_metter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion_color_boost', models.CharField(choices=[('червоний', 'red'), ('зелений', 'green'), ('немає', 'None')], default='None', max_length=200)),
                ('ads_status', models.CharField(choices=[('не модеровано', 'non_moderated'), ('прийнято', 'approved'), ('відхилено', 'denied')], default='non_moderated', max_length=200)),
                ('version_of_calculation', models.CharField(choices=[('кредит', 'credit'), ('тільки готівка', 'only_cash'), ('іпотека', 'mortgage')], max_length=200)),
                ('accomodation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.accomodation')),
                ('denied_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.deniedcause')),
                ('promotion_additional_phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.promoadditionalphrase')),
            ],
        ),
    ]
