# Generated by Django 3.2.21 on 2023-09-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_status', models.CharField(choices=[('new_building', 'новобудова'), ('resale_property', 'вторинне житло'), ('cottage', 'коттедж')], max_length=200)),
                ('number', models.PositiveSmallIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('planing', models.CharField(choices=[('studio_appartment_with_barhroom', 'студія з санвузлом'), ('studio_appartment_with_barhroom_and_one bedroom', 'студія з санвузлом і однією спальнею'), ('two_bedroom', 'двокімнатна'), ('two_bedroom_and_roof', 'двокімнатна зі своєю кришею'), ('three_bedroom', 'трьокімнатна'), ('three_bedroom_and_roof', 'трьокімнатна зі своєю кришею')], max_length=200)),
                ('living_condition', models.CharField(choices=[('need_repair', 'вимагає ремонту'), ('reary_for_settlement', 'готова для заселення')], max_length=200)),
                ('area_kitchen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('have_balcony', models.BooleanField()),
                ('heat_type', models.CharField(choices=[('gas', 'газове'), ('electric', 'електричний'), ('wood_heating', "дров'яне опалення")], max_length=200)),
                ('schema', models.ImageField(blank=True, null=True, upload_to='galery/appartment_schemas/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('is_shown_in_chesboard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_metter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ads_status', models.CharField(choices=[('non_moderated', 'не модеровано'), ('approved', 'прийнято'), ('denied', 'відхилено')], default='non_moderated', max_length=200)),
                ('version_of_calculation', models.CharField(choices=[('credit', 'кредит'), ('only_cash', 'тільки готівка'), ('mortgage', 'іпотека')], default='mortgage', max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_bigger', models.BooleanField(blank=True, null=True)),
                ('is_lifted_in_feed', models.BooleanField(blank=True, null=True)),
                ('is_turbo', models.BooleanField(blank=True, null=True)),
                ('promotion_color_boost', models.CharField(blank=True, choices=[('red', 'червоний'), ('green', 'зелений'), ('None', 'немає')], default='None', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeniedCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type_status', models.CharField(blank=True, choices=[('new_building', 'новобудова'), ('resale_property', 'вторинне житло'), ('cottage', 'коттедж')], max_length=200, null=True)),
                ('filter_disctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('filter_microdisctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('filter_from_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_to_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_from_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_to_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_house_status', models.CharField(blank=True, choices=[('appartments', 'квартири'), ('appartments_with_terrace', 'квартири з терассами'), ('penthouse', 'пентхауз'), ('individual_house', 'індивідуальний будинок')], max_length=200, null=True)),
                ('filter_living_condition', models.CharField(blank=True, choices=[('need_repair', 'вимагає ремонту'), ('reary_for_settlement', 'готова для заселення')], max_length=200, null=True)),
                ('filter_type', models.CharField(choices=[('all', 'всі'), ('resale_property', 'вторинне житло'), ('new_buiding', 'новобудова'), ('cottage', 'коттедж')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galery/image_galery/')),
                ('obj_order', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoAdditionalPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
