# Generated by Django 3.2.21 on 2023-09-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='accomodation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.accomodation'),
        ),
        migrations.AddField(
            model_name='ads',
            name='denied_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.deniedcause'),
        ),
        migrations.AddField(
            model_name='ads',
            name='favorites_for',
            field=models.ManyToManyField(related_name='favourites_adds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='promotion_additional_phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.promoadditionalphrase'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='document',
            field=models.ManyToManyField(to='houses.Document'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.floor'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodation', to='houses.house'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='house_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.housebuilding'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='house_entrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.houseentrance'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='image_field',
            field=models.ManyToManyField(related_name='accomodation', to='ads.ImageGalery'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='riser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.riser'),
        ),
    ]
