# Generated by Django 3.2.20 on 2023-07-16 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='document',
            field=models.ManyToManyField(to='houses.Document'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.floor'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='house_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.housebuilding'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='house_entrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.houseentrance'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='image_field',
            field=models.ManyToManyField(to='ads.ImageGalery'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='riser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.riser'),
        ),
    ]
