# Generated by Django 3.2.20 on 2023-08-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20230808_1607'),
        ('ads', '0003_accomodation_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodation', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='image_field',
            field=models.ManyToManyField(related_name='accomodation', to='ads.ImageGalery'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_status',
            field=models.CharField(choices=[('non_moderated', 'не модеровано'), ('approved', 'прийнято'), ('denied', 'відхилено')], default='non_moderated', max_length=200),
        ),
        migrations.AlterField(
            model_name='ads',
            name='promotion_color_boost',
            field=models.CharField(blank=True, choices=[('red', 'червоний'), ('green', 'зелений'), ('None', 'немає')], default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='version_of_calculation',
            field=models.CharField(choices=[('credit', 'кредит'), ('only_cash', 'тільки готівка'), ('mortgage', 'іпотека')], default='mortgage', max_length=200),
        ),
    ]
