# Generated by Django 3.2.20 on 2023-08-09 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20230808_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
