# Generated by Django 3.2.20 on 2023-08-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_accomodation_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='date_added',
        ),
    ]
