# Generated by Django 3.2.20 on 2023-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20230809_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
