# Generated by Django 3.2.20 on 2023-08-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='accomodation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.accomodation'),
        ),
    ]
