# Generated by Django 3.2.20 on 2023-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_accomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegalery',
            name='obj_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
