# Generated by Django 3.2.20 on 2023-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_imagegalery_obj_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='heat_type',
            field=models.CharField(choices=[('gas', 'газове'), ('electric', 'електричний'), ('wood_heating', "дров'яне опалення")], max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='living_condition',
            field=models.CharField(choices=[('need_repair', 'вимагає ремонту'), ('reary_for_settlement', 'готова для заселення')], max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='planing',
            field=models.CharField(choices=[('studio_appartment_with_barhroom', 'студія з санвузлом'), ('studio_appartment_with_barhroom_and_one bedroom', 'студія з санвузлом і однією спальнею'), ('two_bedroom', 'двокімнатна'), ('two_bedroom_and_roof', 'двокімнатна зі своєю кришею'), ('three_vedroom', 'трьокімнатна'), ('three_vedroom_and_roof', 'трьокімнатна зі своєю кришею')], max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='type_status',
            field=models.CharField(choices=[('new_building', 'новобудова'), ('resale_property', 'вторинне житло'), ('cottage', 'коттедж')], max_length=200),
        ),
    ]
