# Generated by Django 3.2.20 on 2023-08-16 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0011_auto_20230815_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type_status', models.CharField(blank=True, choices=[('new_building', 'новобудова'), ('resale_property', 'вторинне житло'), ('cottage', 'коттедж')], max_length=200, null=True)),
                ('filter_disctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('filter_microdisctrict', models.CharField(blank=True, max_length=200, null=True)),
                ('filter_from_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_to_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_from_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_to_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filter_house_status', models.CharField(blank=True, choices=[('appartments', 'квартири'), ('appartments_with_terrace', 'квартири з терассами'), ('penthouse', 'пентхауз'), ('individual_house', 'індивідуальний будинок')], max_length=200, null=True)),
                ('filter_living_condition', models.CharField(blank=True, choices=[('need_repair', 'вимагає ремонту'), ('reary_for_settlement', 'готова для заселення')], max_length=200, null=True)),
                ('filter_type', models.CharField(choices=[('all', 'всі'), ('resale_property', 'вторинне житло'), ('new_buiding', 'новобудова'), ('cottage', 'коттедж')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
