# Generated by Django 3.2.20 on 2023-08-22 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0014_ads_favorites_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='favorites_for',
        ),
        migrations.AddField(
            model_name='ads',
            name='favorites_for',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
