# Generated by Django 3.2.20 on 2023-08-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_ads_favorites_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_bigger',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='is_lifted_in_feed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='is_turbo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
