# Generated by Django 3.2.21 on 2023-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_accomodation_is_shown_in_chesboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='planing',
            field=models.CharField(choices=[('studio_appartment_with_barhroom', 'студія з санвузлом'), ('studio_appartment_with_barhroom_and_one bedroom', 'студія з санвузлом і однією спальнею'), ('two_bedroom', 'двокімнатна'), ('two_bedroom_and_roof', 'двокімнатна зі своєю кришею'), ('three_bedroom', 'трьокімнатна'), ('three_bedroom_and_roof', 'трьокімнатна зі своєю кришею')], max_length=200),
        ),
    ]
